### ISSUE TITLE
Error while migrate the site

### ISSUE THREAD

**Issue by mohsinalimat** [AgileShift/cargo_management#1]
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in 
main()
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
click.Group(commands=commands)(prog_name='bench')
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 829, in call
return self.main(*args, **kwargs)
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
return f(get_current_context(), *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/init.py", line 27, in _func
ret = f(frappe._dict(ctx.obj), *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 309, in migrate
skip_search_index=skip_search_index
File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 75, in migrate
sync_customizations()
File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 97, in sync_customizations
sync_customizations_for_doctype(data, folder)
File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 153, in sync_customizations_for_doctype
validate_fields_for_doctype(doctype)
File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 740, in validate_fields_for_doctype
validate_links_table_fieldnames(meta)
File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 736, in validate_links_table_fieldnames
frappe.throw(message, InvalidFieldNameError, _("Invalid Fieldname"))
File "/home/frappe/frappe-bench/apps/frappe/frappe/init.py", line 432, in throw
msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
File "/home/frappe/frappe-bench/apps/frappe/frappe/init.py", line 411, in msgprint
_raise_exception()
File "/home/frappe/frappe-bench/apps/frappe/frappe/init.py", line 365, in _raise_exception
raise raise_exception(msg)
frappe.core.doctype.doctype.doctype.InvalidFieldNameError: Row #2: Could not find field warehouse_receipt in Cargo Shipment DocType

**Comment by JeansReal** [comment]
Hello

Issue discused here: https://discuss.erpnext.com/t/link-to-child-table-document-in-dashboard-v13/71572/4

The team has commited a change, but i am not able to make it work
https://github.com/frappe/frappe/pull/13823#issue-700688576

**Comment by JeansReal** [comment]
Problem solved in frappe from v13.36.0

**Comment by JeansReal** [comment]
Problem solved in frappe. from release v13.36.0

frappe/frappe/issues/17899


Please Update the Latest v13 Release
[Version 13 - End Of Life](https://github.com/frappe/frappe/releases/tag/v13.58.21)
